bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements:
- accelerate==0.14.0
- bitsandbytes==0.35.4
- torch==1.13.0
- transformers==4.24.0
resources:
  cpu: "3"
  memory: 15Gi
  use_gpu: true
secrets: {}
spec_version: '2.0'
system_packages: []
